--
-- PostgreSQL database dump
--

\restrict 0Cf96XVgGdmND0SJ12CcovPNVMBUK9i9h1loUZbIX9GWnJdt0sCjJM4yz1vdrgc

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

-- Started on 2026-01-21 10:13:44

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 224 (class 1259 OID 32816)
-- Name: cart_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cart_items (
    id bigint NOT NULL,
    quantity integer,
    size character varying(255),
    product_id bigint,
    user_id bigint
);


ALTER TABLE public.cart_items OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 32815)
-- Name: cart_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cart_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 32857)
-- Name: hero_images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.hero_images (
    id bigint NOT NULL,
    image_url character varying(255)
);


ALTER TABLE public.hero_images OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 32856)
-- Name: hero_images_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.hero_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hero_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 32850)
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    order_date timestamp(6) without time zone,
    total_price double precision
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 32849)
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 32791)
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    category character varying(255),
    image_url character varying(255),
    name character varying(255) NOT NULL,
    price double precision NOT NULL,
    description character varying(1000)
);


ALTER TABLE public.products OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 32790)
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 32802)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 32801)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 32823)
-- Name: wishlist; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wishlist (
    id bigint NOT NULL,
    product_id bigint,
    user_id bigint
);


ALTER TABLE public.wishlist OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 32822)
-- Name: wishlist_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wishlist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wishlist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4950 (class 0 OID 32816)
-- Dependencies: 224
-- Data for Name: cart_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cart_items (id, quantity, size, product_id, user_id) FROM stdin;
\.


--
-- TOC entry 4956 (class 0 OID 32857)
-- Dependencies: 230
-- Data for Name: hero_images; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.hero_images (id, image_url) FROM stdin;
4	https://static.vecteezy.com/system/resources/thumbnails/046/535/084/large/men-s-clothing-store-display-a-neatly-organized-display-of-men-s-clothing-in-a-store-showcasing-a-variety-of-shirts-blazers-and-folded-garments-on-shelves-and-racks-video.jpg
5	https://media.istockphoto.com/id/916092484/photo/women-clothes-hanging-on-hangers-clothing-rails-fashion-design.jpg?s=612x612&w=0&k=20&c=fUpcbOITkQqitglZfgJkWO3py-jsbuhc8eZfb4sdrfE=
6	https://t4.ftcdn.net/jpg/01/51/50/57/360_F_151505758_4K7LAAL9wkuWiXRTnSeFbmnPVtntsvKn.jpg
\.


--
-- TOC entry 4954 (class 0 OID 32850)
-- Dependencies: 228
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders (id, order_date, total_price) FROM stdin;
1	2026-01-20 20:50:55.956249	37500
2	2026-01-21 00:48:55.944767	7500
\.


--
-- TOC entry 4946 (class 0 OID 32791)
-- Dependencies: 220
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (id, category, image_url, name, price, description) FROM stdin;
10	KIDS	https://doodlechic.in/cdn/shop/files/1_8d7e37f6-4f6d-46a5-98d1-cb314341f78c.png?v=1714046895	White printed t-shirt	5500	100% Organic Cotton Tshirt for Kids
13	KIDS	https://finebrandz.lk/cdn/shop/products/23P3089C5786I---20B_2000x.jpg?v=1680065771	Cotton Blue T Shirt	6550	A summertime classic, UCB's light blue polo t-shirt for kids comes with a basic solid design. Breathable and light, this shirt is stitched from a 100% cotton which ensures a comfortable everyday wear.
14	KIDS	https://www.polo.co.za/api/catalog/product/0/0/0063353_boys_bongani_printed_ss_tee_navy_21961.jpg?store=default&image-type=image	Printed Short Sleeve T-shirt	7500	Add quality your child's style with this premium boys' T-shirt, crafted from 100% cotton for all-day comfort. Perfect for any adventure!
15	WOMAN	https://coolplanet.lk/cdn/shop/files/009_d9079615-a154-4798-86ee-f2f19eb9dd43.jpg?v=1756980019&width=1946	Andriana FORMALITE Women's Office Dress	3950	Elegant
16	WOMAN	https://coolplanet.lk/cdn/shop/files/2_55bb76d3-d9b2-4653-bb67-a09c61b41160.jpg?v=1757494260&width=1946	Envogue Ladies Casual Blouse	4500	Beautiful
17	WOMAN	https://coolplanet.lk/cdn/shop/files/29_139a7b02-20bb-4d9e-a005-8467202a7909.jpg?v=1757406314&width=1946	Modano Casual Printed T-Shirt	2570	"Outfit on point, the mood on top."
18	MAN	https://coolplanet.lk/cdn/shop/files/113_170d72fd-a640-434b-b636-4b1b7769feff.jpg?v=1763449737&width=1946	Hustle Men's Casual T-Shirt	2630	Hustle
19	MAN	https://coolplanet.lk/cdn/shop/files/22_05afb482-2191-4f4e-99fb-ae208269f4fd.jpg?v=1760694724&width=1946	Hustle men's Denim Shirt	6500	Hustle men's Denim
20	MAN	https://coolplanet.lk/cdn/shop/files/WEB3_0000s_0036__61.jpg?v=1767766965&width=1946	King Street Men’s Slim Fit Long Sleeve Casual Shirt	5530	King Street
\.


--
-- TOC entry 4948 (class 0 OID 32802)
-- Dependencies: 222
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, password, role, username) FROM stdin;
1	$2a$10$qG45yNDTKtSMTeJhQQm64O83O.ziQB17ommFI962i8xgLtLQpxqAC	ADMIN	admin
2	$2a$10$2f9tbiIJ5bQ3uTVvyxUS9.uphjeH8Na/HkMIEU0oqGZ.qTLvgxZ5q	CUSTOMER	Dexter
\.


--
-- TOC entry 4952 (class 0 OID 32823)
-- Dependencies: 226
-- Data for Name: wishlist; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.wishlist (id, product_id, user_id) FROM stdin;
\.


--
-- TOC entry 4962 (class 0 OID 0)
-- Dependencies: 223
-- Name: cart_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cart_items_id_seq', 1, true);


--
-- TOC entry 4963 (class 0 OID 0)
-- Dependencies: 229
-- Name: hero_images_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.hero_images_id_seq', 6, true);


--
-- TOC entry 4964 (class 0 OID 0)
-- Dependencies: 227
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_id_seq', 2, true);


--
-- TOC entry 4965 (class 0 OID 0)
-- Dependencies: 219
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_id_seq', 20, true);


--
-- TOC entry 4966 (class 0 OID 0)
-- Dependencies: 221
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 2, true);


--
-- TOC entry 4967 (class 0 OID 0)
-- Dependencies: 225
-- Name: wishlist_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.wishlist_id_seq', 1, true);


--
-- TOC entry 4787 (class 2606 OID 32821)
-- Name: cart_items cart_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);


--
-- TOC entry 4793 (class 2606 OID 32862)
-- Name: hero_images hero_images_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hero_images
    ADD CONSTRAINT hero_images_pkey PRIMARY KEY (id);


--
-- TOC entry 4791 (class 2606 OID 32855)
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- TOC entry 4781 (class 2606 OID 32800)
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- TOC entry 4783 (class 2606 OID 32814)
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- TOC entry 4785 (class 2606 OID 32812)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4789 (class 2606 OID 32828)
-- Name: wishlist wishlist_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT wishlist_pkey PRIMARY KEY (id);


--
-- TOC entry 4794 (class 2606 OID 32829)
-- Name: cart_items fk1re40cjegsfvw58xrkdp6bac6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fk1re40cjegsfvw58xrkdp6bac6 FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- TOC entry 4796 (class 2606 OID 32839)
-- Name: wishlist fk6p7qhvy1bfkri13u29x6pu8au; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT fk6p7qhvy1bfkri13u29x6pu8au FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- TOC entry 4795 (class 2606 OID 32834)
-- Name: cart_items fk709eickf3kc0dujx3ub9i7btf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fk709eickf3kc0dujx3ub9i7btf FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4797 (class 2606 OID 32844)
-- Name: wishlist fktrd6335blsefl2gxpb8lr0gr7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT fktrd6335blsefl2gxpb8lr0gr7 FOREIGN KEY (user_id) REFERENCES public.users(id);


-- Completed on 2026-01-21 10:13:44

--
-- PostgreSQL database dump complete
--

\unrestrict 0Cf96XVgGdmND0SJ12CcovPNVMBUK9i9h1loUZbIX9GWnJdt0sCjJM4yz1vdrgc

